packages:
  - "apps/*"
  - "nest-lib/*"
  - "packages/*"
  - "tools/*"
  - "clis/*"

catalog:
  "@nestjs/common": "^11.0.10"
  "@nestjs/core": "^11.0.10"
  "@nestjs/platform-express": "^11.0.10"
  "@nestjs/mongoose": "^11.0.1"
  "mongoose": "^8.10.1"
#  "@mono/nest-config": "^1.0.0"
#  "@mono/nest-adding-module": "^1.0.0"
  # "@mono/nest-config": "file:./pack/mono-nest-config-1.0.0.tgz"
  # "@mono/nest-adding-module": "file:./pack/mono-nest-adding-module-1.0.0.tgz"
